server:
  port: 7000
spring:
  datasource:
    url: jdbc:sqlite:bridge.db
    #url: "jdbc:sqlite::memory:"
    driver-class-name: org.sqlite.JDBC
  jpa:
    show_sql: false
    database-platform: org.hibernate.dialect.SQLiteDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
logging:
  level:
    org:
      springframework:
        web: WARN
        hibernate: WARN
        boot:
          web:
            servlet: WARN
    com:
      vaadin:
        spring:
          boot:
            internal: WARN
webbridge:
# Set to 'true' to remove data from the database at startup
  cleardatabase: true
# Set to 'true' to enable loading data from XLSX file at startup
  loadBidsFromXlsx: true
  writeBidsToXlsx: false
vaadin:
  servlet:
    productionMode: false
    heartbeatInterval: 60
---
spring:
  profiles: production
server:
  port: 9000
  ssl:
    key-store: classpath:bridge.p12
    key-store-password: haselkobridge
    ssl.key-password: haselkobridge
vaadin:
  servlet:
    productionMode: true
    heartbeatInterval: 90
